apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: geiaus-server
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: geiaus-server
    spec:
      containers:
      - name: geiaus-server
        image: gcr.io/nich01as-com/geiaus-server:20160626-01
        ports:
        - containerPort: 50051 
        imagePullPolicy: Always
